docs/index.adoc, include/stdx/intrusive_list.hpp, test/CMakeLists.txt, test/intrusive_list.cpp
A simple doubly-linked intrusive list. Notably it only provides forward iteration, to avoid complexity in handling reverse iterators. However it does allow pushing and popping at both ends.
=> :sparkles: Add intrusive_list

CMakeLists.txt, docs/index.adoc, include/stdx/ct_string.hpp, include/stdx/panic.hpp, test/CMakeLists.txt, test/ct_string.cpp, test/default_panic.cpp, test/panic.cpp
`panic` is used for various unrecoverable cases - usually precondition violations - inside `stdx` instead of calling `assert` or throwing exceptions.
=> :sparkles: Add panic function

docs/bitset.adoc, include/stdx/bitset.hpp, test/CMakeLists.txt, test/bitset.cpp
- Construct with set bit values
- Fix constructor from string_view
- Update & improve docs
=> Bitset changes

include/stdx/tuple.hpp, include/stdx/tuple_algorithms.hpp, test/CMakeLists.txt, test/tuple.cpp, test/tuple_algorithms.cpp
- comparing tuples containing references
- transforming tuples containing refererences
=> Fixes for references in tuples

docs/bit.adoc, include/stdx/bit.hpp, test/bit.cpp
Folks implementing cryptography might use `byteswap`. For the rest of us, writing e.g. network protocol handlers, `to_le` and `to_be` are much more useful. They should really be in the standard.
=> :sparkles: Add `to_be` and `to_le`

docs/type_traits.adoc, include/stdx/type_traits.hpp, test/fail/CMakeLists.txt, test/fail/template_for_each_not_list.cpp, test/type_traits.cpp
Instantiating a tuple of empty objects just to use `for_each` with the types seems wasteful. `type_list` and `value_list` are useful in general.
=> :sparkles: Add `template_for_each`

include/stdx/tuple.hpp, include/stdx/type_traits.hpp, test/fail/CMakeLists.txt, test/fail/tuple_equality_mismatch.cpp, test/fail/tuple_equality_with_element.cpp, test/fail/tuple_spaceship_mismatch.cpp, test/fail/tuple_spaceship_with_element.cpp, test/indexed_tuple.cpp, test/tuple.cpp, test/tuple_algorithms.cpp
- tuples of references should not compare addresses
- comparing tuples of mismatched sizes (by pack expansion of the shorter pack!) should not compile
- comparing a tuple to one of its elements (by implicit conversion to base!) should not compile
=> :bug: Fix tuple equality

docs/concepts.adoc, include/stdx/concepts.hpp, test/concepts.cpp
It's annoying to write boilerplate concepts to constrain by type traits. `has_trait` fixes that.
=> :sparkles: Add `has_trait` concept

include/stdx/bitset.hpp, test/bitset.cpp
This is useful when using a bitset to keep track of used/unused elements.
=> :sparkles: Add bitset::lowest_unset

docs/concepts.adoc, docs/type_traits.adoc, include/stdx/concepts.hpp, include/stdx/type_traits.hpp, test/concepts.cpp, test/type_traits.cpp
A useful concept that matches two types if they are the same after applying `remove_cvref` to both.
=> :sparkles: Add `same_as_unqualified`

include/stdx/optional.hpp, test/optional.cpp
- variadic transform was just wrong
- neither member-function nor variadic transform dealt with nonmovable types
- optional pointers have a default sentinel of nullptr
=> Fix optional transform, add nullptr as sentinel for optional pointers

docs/tuple_algorithms.adoc, include/stdx/tuple_algorithms.hpp, test/tuple_algorithms.cpp
`enumerate` is just like `for_each`, but calls the provided function object with an NTTP representing the index.
=> :sparkles: Add tuple enumerate

docs/bit.adoc, include/stdx/bit.hpp, test/bit.cpp
I've written this in various places now. Call-site bit twiddling is tedious, especially dealing with a) integer promotion rules and b) shift-by-the-bit-size-of-the-type is UB.
=> :sparkles: Add `bit_mask`

docs/bit.adoc, include/stdx/bit.hpp, test/bit.cpp
Much more readable and discoverable than something like `std::numeric_limits<T>::digits + std::numeric_limits<T>::is_signed`.
=> :sparkles: Add `bit_size`

docs/type_traits.adoc, docs/utility.adoc, include/stdx/concepts.hpp, include/stdx/optional.hpp, include/stdx/type_traits.hpp, include/stdx/utility.hpp, test/concepts.cpp, test/optional.cpp, test/type_traits.cpp
It's useful to be able to construct a `stdx::optional<std::string_view>`.
=> :sparkles: Add support for non-structural types as NTTPs

docs/ct_string.adoc, include/stdx/ct_string.hpp, test/ct_string.cpp
Problem:
- `ct_string` stores an internal array including a null terminator, but `size` reports the string length without the null terminator. This on its own is OK, but...
- iterating a `ct_string` required using begin and end on the underlying `value` (the array including the null terminator). Therefore `size` was at odds with the number of items iterated.
Solution:
- Add `begin` and `end` for ct_string that allow direct iteration and agree with `size`. Similarly, `rbegin` and `rend` to allow reverse iteration excluding the null terminator.
=> :children_crossing: Make ct_string interface safer with begin/end

docs/bitset.adoc, include/stdx/bitset.hpp, test/bitset.cpp, test/fail/bitset_to_uint64_over_64_bits.cpp
Remove `to_uint64_t`; it's superseded.
=> :sparkles: Add `bitset::to<T>` for conversion to unsigned integral

include/stdx/tuple.hpp, test/tuple_algorithms.cpp
We often write plain indexed for loops in order to work on two arrays... here's a better way.
=> :art: Enable `for_each` on `std::array`

docs/algorithm.adoc, docs/tuple_algorithms.adoc, include/stdx/algorithm.hpp, include/stdx/tuple.hpp, include/stdx/tuple_algorithms.hpp, test/algorithm.cpp, test/tuple_algorithms.cpp
- Add variadic `for_each`
- Change tuple `for_each` to be `unrolled_for_each` on arrays
- Add `unrolled_enumerate` for arrays
- Constrain tuple algorithms
=> :sparkles: Add `for_each` and `for_each_n` to algorithms

include/stdx/concepts.hpp, include/stdx/ct_string.hpp, include/stdx/detail/list_common.hpp, include/stdx/intrusive_forward_list.hpp, include/stdx/intrusive_list.hpp, include/stdx/ranges.hpp, include/stdx/tuple.hpp, include/stdx/tuple_algorithms.hpp, test/CMakeLists.txt, test/concepts.cpp, test/intrusive_list_properties.cpp, test/ranges.cpp
Problem:
- Profiling shows the following includes to be particularly expensive:
- `<iterator>`
- `<memory>`
Solution:
- Remove uses of `std::begin()`, `std::end()` etc in favour of the member functions where possible.
- Remove uses of `std::addressof()` where possible.
- Move the `range` concept from `concepts.hpp` to `ranges.hpp`. Using `std::begin` and `std::end` here is preferable so that C-style arrays model `range`. But it need not be included by default in `concepts.hpp`: this also matches the standard better.
Note:
- This is a breaking change since the `range` concept moved.
=> :zap: :boom: Remove some expensive includes

docs/bit.adoc, include/stdx/bit.hpp, include/stdx/bitset.hpp, test/fail/bitset_signed_storage.cpp
What used to be `detail::select_storage`
=> :sparkles: Add `smallest_uint`

include/stdx/ct_format.hpp, include/stdx/utility.hpp, test/ct_format.cpp
Formatting of:
- type-encoded strings
- already-computed format results
=> :sparkles: Allow more compile-time formatting use cases

include/stdx/ct_format.hpp, test/ct_format.cpp
In order to call `ct_format` with runtime arguments, it can't be `consteval`!
=> :bug: Back off the consteval fervour

include/stdx/span.hpp
When a span is constructed from a range, it's not necessarily lifetimebound to that range. That range might be another view type, in which case it's OK for the span to outlive it - as long as the span doesn't outlive the underlying data.
=> :bug: Remove incorrect `LIFETIMEBOUND` annotation

include/stdx/concepts.hpp
This code path was not well-exercised and had trivial bugs.
=> :bug: Fix concepts when C++ standard library is lacking

include/stdx/bit.hpp, include/stdx/byterator.hpp, include/stdx/memory.hpp, test/CMakeLists.txt, test/byterator.cpp
Problem:
- It is a common case to have a table of &lt;unsigned words&gt; from which we want to read &lt;arbitrary-size unsigned quantity&gt; as we interpret the table. For example, an array of std::uint32_t where we read some things as 16-bit, some things as 8-bit, etc.
Solution:
- Add `byterator` - an iterator-like type that allows extra read/write operations. It behaves like a random access iterator (to `std::byte`) but also has operations to peek, read and write arbitrary trivially-copyable types.
=> :sparkles: Add `byterator`

docs/type_traits.adoc, include/stdx/type_traits.hpp, test/type_traits.cpp
Problem:
- Expanding a type list into a pack of template arguments involves too much call-site boilerplate.
Solution:
- Add `apply_sequence` which is very similar to `template_for_each`, but instead of iterating the list, it passes the list contents as a pack.
=> :new: Add `apply_sequence`

include/stdx/tuple.hpp
`cib` uses transform on a single tuple adding an index. The single-arg transform overload did not allow indexing, so this was using the slower-to-compile more general form of transform.
This change saves ~30% of the transform time for the cib benchmark.
=> :zap: Improve compile time for a common transform use case

include/stdx/tuple.hpp, include/stdx/tuple_algorithms.hpp
On my laptop, this saves another ~8% on the CIB compilation benchmark total time.
=> :zap: Use `__type_pack_element` to speed up tuple indexing

include/stdx/ct_string.hpp
GCC and clang allow a user-defined literal operator template with the signature:
```cpp
template <typename T, T...> auto operator""_udl();
```
This is a non-standard extension and for our purposes at least it is replaced in C++20 by using an operator template with a structural NTTP:
```cpp
template <ct_string S> auto operator""_udl();
```
=> :art: Don't use nonstandard UDL extension

docs/tuple_algorithms.adoc, include/stdx/tuple_algorithms.hpp, test/tuple_algorithms.cpp
This replaces `sort | chunk_by` as used by CIB. This improves the CIB compilation benchmark: `gather_by` is roughly 1.4x faster than `sort | chunk_by`.
=> :zap: Add `gather_by` for tuples

include/stdx/ct_string.hpp, include/stdx/type_traits.hpp, test/ct_string.cpp, test/type_traits.cpp
- `cts_t` packages a `ct_string` inside a type.
- `shrink_t` and `expand_t` are for relieving some compilation woes in handling long type names.
=> :sparkles: Add `cts_t`, `shrink_t` and `expand_t`

docs/tuple_algorithms.adoc, include/stdx/tuple_algorithms.hpp, test/tuple_algorithms.cpp
Making a tuple of one element just to call `tuple_cat` is cumbersome. Why not use `tuple_cons`/`tuple_snoc`? Or for non-lispers, `tuple_push_front` and `tuple_push_back`?
=> :sparkles: Add `tuple_cons` and `tuple_snoc`

include/stdx/tuple.hpp, test/tuple.cpp
Problem:
- Putting class types into a tuple uses inheritance.
- A tuple inside a tuple may produce the same base type more than once in the tree, leading to indexing ambiguity.
Solution:
- Use composition only, not inheritance, for tuple elements.
=> :bug: Fix possible ambiguity in tuple indexing

docs/ct_conversions.adoc, include/stdx/compiler.hpp, include/stdx/ct_string.hpp, include/stdx/utility.hpp, test/fail/CMakeLists.txt, test/fail/ct_check.cpp
Problem:
- There is no way to produce a user-formatted compile-time diagnostic.
Solution:
- Add `ct_check` to test a condition at compile-time and produce a `ct_string`
message on failure.
Note:
- A constraint check is the key to prevent the compiler from eliding the string.
=> :sparkles: Add compile-time diagnostic `ct_check`

docs/bitset.adoc, include/stdx/bitset.hpp, include/stdx/type_traits.hpp, test/bitset.cpp
Problem:
- A `bitset` cannot be specified with enumeration values, nor have bits set/reset using them.
Solution:
- Allow specifying and manipulating a bitset using enumeration values as the bits.
=> :sparkles: Allow using `bitset` with enum values

.github/workflows/unit_tests.yml, mull.yml, test/CMakeLists.txt, test/ct_format.cpp, test/cx_map.cpp, test/cx_multimap.cpp, test/cx_set.cpp, test/cx_vector.cpp, test/function_traits.cpp, test/intrusive_forward_list.cpp, test/intrusive_list.cpp, test/intrusive_list_properties.cpp, test/numeric.cpp, test/optional.cpp, test/panic.cpp, test/tuple.cpp, test/tuple_algorithms.cpp, test/type_traits.cpp, test/with_result_of.cpp
Problem:
- Quis custodiet ipsos custodies? (Who tests the tests?)
Solution:
- Mutation testing tests the tests.
Note:
- To run mutation tests, build the `mull_tests` target.
- Mull tests are run as a CI job but this doesn't gate `merge_ok`.
- The CI job runs mutations tests on ubuntu-22.04, LLVM 15, mull v0.23.0. This is the current "latest version" taking into consideration the constraints. When we run on ubuntu-24.04, we can use LLVM 17 for mull. And later versions as they are supported.
=> :construction_worker: Add mutation tests

include/stdx/ct_string.hpp, test/fail/ct_check.cpp
Problem:
- It's useful to assign the result of `ct_check::emit` to a declared variable in cases where we aren't inside a function. For example, a fallback instantiation of a class template that wants to emit an error can declare a member variable.
Solution:
- Return a value from `ct_check::emit`.
=> :art: Return a value from `ct_check::emit`

docs/tuple.adoc
=> :books: :bug: Fix out-of-date tuple docs

.github/workflows/unit_tests.yml, CMakeLists.txt, docs/atomic_bitset.adoc, docs/bitset.adoc, docs/index.adoc, docs/intro.adoc, docs/intrusive_forward_list.adoc, docs/ranges.adoc, include/stdx/atomic_bitset.hpp, include/stdx/bit.hpp, include/stdx/bitset.hpp, include/stdx/detail/bitset_common.hpp, test/CMakeLists.txt, test/atomic_bitset.cpp, test/bitset.cpp, test/fail/bitset_signed_storage.cpp
Problem:
- It is useful to have atomic semantics on a bitset.
Solution:
- Add `atomic_bitset`.
Notes:
- `std::atomic<stdx::bitset<N, std::uintXX_t>>` is unwieldy and could not guarantee the use of atomic instructions.
- `stdx::bitset<N, std::atomic<std::uintXX_t>>` would not provide the right atomic semantics.
- The API of `atomic_bitset` differs from the API of `bitset` in some important ways, but is intended to provide for the use case of effectively using an atomic integral type as a bitset.
=> :sparkles: Add `atomic_bitset`

CMakeLists.txt, docs/atomic.adoc, docs/index.adoc, docs/intro.adoc, include/stdx/atomic.hpp, test/CMakeLists.txt, test/atomic.cpp, test/atomic_bitset.cpp, test/atomic_bitset_override.cpp, test/atomic_override.cpp, test/detail/atomic_cfg.hpp, test/fail/CMakeLists.txt, test/fail/atomic_bool_dec.cpp
Problem:
- Using `std::atomic` does not necessarily produce good codegen for microcontroller platforms.
Solution:
- Add `stdx::atomic` which uses the customizable atomic interface from the baremetal concurrency library.
=> :sparkles: Add `atomic`

docs/ct_conversions.adoc, docs/ct_string.adoc, include/stdx/ct_string.hpp, test/fail/CMakeLists.txt, test/fail/static_assert.cpp
Problem:
- `ct_check<cond>.template emit<msg>()` is not so ergonomic to use.
Solution:
- Add `STATIC_ASSERT` which does approximately the same thing, but in a more easy-to-use form.
=> :art: Add `STATIC_ASSERT`

docs/static_assert.adoc, include/stdx/static_assert.hpp, test/fail/static_assert_format.cpp
Problem:
- `STATIC_ASSERT("{}", 42)` should be allowed, because `42` can be a template argument.
Solution:
- Allow it.
=> :art: Allow bare template arguments in `STATIC_ASSERT`

include/stdx/tuple.hpp, include/stdx/udls.hpp, test/udls.cpp
Problem:
- The `_c` UDL doesn't deal with digit separators.
Solution:
- Fix it.
=> :bug: Allow UDL to work with digit separators

include/stdx/ct_string.hpp
Problem:
- `string_view`'s constructor takes a `char const *` and a size, not an iterator and a size. On platforms where an array iterator is not a simple pointer, this fails.
Solution:
- Use `data` instead of `cbegin` to access the string data.
=> :bug: Fix `string_view` construction

include/stdx/cx_map.hpp, include/stdx/cx_set.hpp, include/stdx/cx_vector.hpp
Problem:
- Container classes define `iterator` as a pointer type but return `begin()` or `end()` of the underlying `std::array`, which is an iterator type, not necessarily a pointer.
Solution:
- Use `data()` instead of `begin()` where necessary.
=> :bug: Don't assume `std::array<>::iterator` is a pointer

CMakeLists.txt
AppleClang 
```
/usr/bin/g++ --version
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
/usr/bin/clang++ --version
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
complains about missing braces as
```
[ 50%] Building CXX object test/cib/CMakeFiles/cib_nexus_test.dir/nexus.cpp.o
cd "build/Clang 16.0.0 arm64-apple-darwin24.1.0/test/cib" && /usr/bin/clang++ -DFMT_HEADER_ONLY=1 -Iinclude -isystem "build/Clang 16.0.0 arm64-apple-darwin24.1.0/_deps/catch2-src/src/catch2/.." -isystem "build/Clang 16.0.0 arm64-apple-darwin24.1.0/_deps/catch2-build/generated-includes" -isystem …
```
=> Ignore missing-braces warnings for AppleClang similar to Clang

include/stdx/byterator.hpp, test/byterator.cpp
Problem:
- Byterator supports e.g. `peek<std::uint8_t, E>()` but not `peeku8<E>()`.
Solution:
- Add return type control to the alias functions.
=> :art: Add return type control to `byterator` peek/read aliases

include/stdx/atomic_bitset.hpp, test/atomic_bitset.cpp
Problem:
- `reset(bit)` does not take an order to apply.
- `flip` does not allow bit ranges like `set` and `reset` do.
Solution:
- Give `reset(bit)` an order argument.
- Provide `flip` overloads to match `set` and `reset`.
=> :bug: Fix `atomic_bitset::reset` for order

include/stdx/ct_format.hpp, include/stdx/ct_string.hpp, include/stdx/static_assert.hpp, include/stdx/utility.hpp, test/ct_format.cpp, test/ct_string.cpp, test/utility.cpp
Problem:
- `ct_format` produces a type that is either a `ct_string` or a `format_result`, which means all client code needs to check that.
- `ct_format` works at compile-time but produces a string value that may lose its `constexpr` nature, so can't be put into a type.
Solution:
- Always return a `format_result` (possibly with an empty tuple).
- Wrap the returned `ct_string` in a type.
=> :art: Preserve `ct_format` string types

include/stdx/ct_format.hpp, test/ct_format.cpp
Problem:
- Can't easily format a `format_result` even though it has a compile-time string inside it.
Solution:
- Allow this.
=> :bug: Fix formatting a `format_result`

docs/bit.adoc, include/stdx/bit.hpp, test/bit.cpp
Problem:
- It is counterintuitive (although representationally correct) to use `to_be` to do the job of both `htonl` and `ntohl`.
Solution:
- Add `from_be` and `from_le` to match `to_be` and `to_le`.
=> :sparkles: Add `from_le` and `from_be`

include/stdx/ct_string.hpp, include/stdx/utility.hpp, test/ct_string.cpp, test/utility.cpp
Problem:
- `ct` must use a function template to obtain overloads for both type template parameters and NTTPs. However when using `ct` with an NTTP placeholder type there is an ambiguity if the NTTP is not deduced: both the `auto` overload and the `ct_string` overloads match.
Solution:
- Introduce another NTTP placeholder type, `ct_helper` that can be partially specialized without definition to disable the primary template specialization.
=> :bug: Fix ambiguity with `ct`

.github/workflows/asciidoctor-ghpages.yml, include/stdx/ct_format.hpp, include/stdx/ct_string.hpp, test/ct_format.cpp
Problem:
- `ct_format` produces a `format_result` in all cases. In some cases the runtime argument tuple is empty and it is convenient to be able to convert implicitly to a `ct_string`.
Solution:
- Allow implicit conversion from a `format_result` to a `ct_string` in the case where there are no runtime arguments and the `format_result` contains only a `ct_string`.
=> :art: Allow implicit conversion of `format_result` to `ct_string`

docs/bitset.adoc, include/stdx/bitset.hpp, test/bitset.cpp
Problem:
- It is relatively common to want to do for_each on a bitset, but also capture whether or not the action succeeded at all, e.g. when handling a message with an indexed handler.
Solution:
- Add `transform_reduce` on bitset.
Note:
- Both `for_each` and `transform_reduce` are applicable variadically, however this is not yet implemented. But this is the reason that the bitset is the final argument.
- There are some differences (for the better) from the `std::transform_reduce` API.
- The transform function comes before the reduction function. `std::transform_reduce` is confusing, because the transform happens first but is given second.
- The type of the `init` value can be easily given in a template argument; this is helpful for avoiding warnings when passing `0` (an `int`) to …
=> :sparkles: Add `transform_reduce` on bitset

include/stdx/bitset.hpp, test/bitset.cpp
When using a `bitset` with an `enum`, it makes sense that the function passed to `for_each` should take an `enum` value.
=> :art: Preserve enum values in bitset `for_each`

include/stdx/static_assert.hpp, test/fail/CMakeLists.txt
Problem:
- `STATIC_ASSERT` before C++26 relies on some interesting compiler behaviour; although it gives the right message, it's not obvious in the compilation output.
- When C++26 `static_assert` is available, use that. The resulting compiler output is typically much more straightforward.
=> :sparkles: Support C++26 `static_assert`

CMakeLists.txt, include/stdx/env.hpp, test/CMakeLists.txt, test/env.cpp
Problem:
- CIB log env is a generic component that is useful beyond logging and should live in stdx.
Solution:
- Add `stdx::env`.
Note:
- For the moment this is dealing with compile-time values only. It may be possible in future to unify this with runtime environments used by S&R.
=> :sparkles: Add `env` to hold compile-time values

include/stdx/env.hpp, test/env.cpp
Problem:
- There is no way to override one environment with another.
- There is no concept to identify an environment type.
Solution:
- Add `append_env_t`.
- Add `envlike`.
=> :sparkles: Add useful things for environment handling

docs/type_traits.adoc, include/stdx/env.hpp, include/stdx/function_traits.hpp, include/stdx/type_traits.hpp, test/type_traits.cpp
Problem:
- It's annoying to make a type list just to index into it.
- Boost.MP11 doesn't provide `mp_at` that works on value lists.
Solution:
- Introduce `nth_t<Index, Ts...>` and `nth_v<Index, Vs...>` to give the nth type or value of a pack respectively.
=> :sparkles: Add `nth_t` and `nth_v`

include/stdx/env.hpp, test/env.cpp
Problem:
- When extending or appending environments it's easy for the type to balloon in size.
Solution:
- Strip duplicate queries from an environment.
=> :art: Keep environment types as small as possible

include/stdx/env.hpp, include/stdx/span.hpp, include/stdx/type_traits.hpp, test/env.cpp
Problem:
- Upgrading to clang-20 flags a couple of issues.
Solution:
- Fix the issues.
=> :art: Small fixes from clang-20

include/stdx/concepts.hpp, test/concepts.cpp
Problem:
- There in no concept that expresses a variadic `same`-style check.
Solution:
- Add `same_any` and `same_none`.
=> :sparkles: Add `same_any` and `same_none` concepts

include/stdx/atomic.hpp, test/atomic_override.cpp, test/detail/atomic_cfg.hpp
Problem:
- Configuring `stdx::atomic` for scoped enumerations doesn't work because a scoped enumeration is not convertible to its configured underlying type.
Solution:
- Instead of requiring convertibility, require the types to be trivially copyable, and that the size & alignment is compatible.
=> :bug: Make `atomic` config work with scoped enumerations

docs/bit.adoc, include/stdx/bit.hpp, test/bit.cpp
Problem:
- There is no way to ask for a bit mask in a `std::array`, such that e.g. `bit_mask<std::array<std::uint8_t, 3>>()` has all 24 bits set.
Solution:
- Make `bit_mask` able to return a `std::array`.
Note:
- This is a building block for array fields in messages among other things.
=> :art: Enable `bit_mask` with array types

include/stdx/ct_format.hpp, test/ct_format.cpp
Problem:
- There is no way for a caller to easily know how many format specifiers are in a string. This is already known to `ct_format` internally, and is useful information to callers.
Solution:
- Add `num_fmt_specifiers`.
Note:
- This is a building block for `CIB_FATAL`, allowing extra arguments to be passed along to `stdx::panic`.
=> :sparkles: Add `num_fmt_specifiers`

.github/workflows/unit_tests.yml, include/stdx/atomic_bitset.hpp, include/stdx/byterator.hpp, include/stdx/rollover.hpp
Problem:
- clang-20 is stable and not yet used to compile this repo.
Solution:
- Add clang-20 support to CI.
=> :construction_worker: Add clang-20 support

docs/algorithm.adoc, include/stdx/algorithm.hpp, include/stdx/tuple.hpp, test/algorithm.cpp, test/tuple.cpp
Problem:
- There is no algorithm that does `for_each` on a range except for the last N
elements.
- There is a use case for a tripartite operation on a range: one operation for
the initial element, another operation for each medial element, and a third
operation for the final element.
- The return values of `for_each` and `for_each_n` do not follow the law of
Useful Return.
Solution:
- Add `for_each_butlastn`, `for_each_butlast`, and `initial_medial_final`.
- Return all useful information from `for_each` and `for_each_n`.
=> :sparkles: Add `for_each_butlast` and `initial_medial_final`

include/stdx/algorithm.hpp
Problem:
- Tuple destructuring is used by `initial_medial_final`.
- Destructuring `stdx::tuple` requires including `<stdx/tuple_destructure.hpp>` which includes `<tuple>`.
Solution:
- Remove the destructuring; use `get` instead.
Closes #218
=> :bug: Remove dependency on tuple destructuring

include/stdx/ct_format.hpp, test/ct_format.cpp
Problem:
- `ct_format` does not allow for compile-time formatting of user-defined types.
Solution:
- Add `ct_format_as` customization point that allows user-defined types to be given customized compile-time formatting.
=> :sparkles: Allow user-defined formatting with `ct_format`

include/stdx/byterator.hpp, test/byterator.cpp
Problem:
- A `byterator` can be equality-compared with a regular iterator, but it cannot be compared for less/greater.
Solution:
- Add comparison operators between `byterator` and corresponding iterators.
=> :sparkles: Add iterator comparisons to `byterator`

include/stdx/byterator.hpp, test/byterator.cpp
Problem:
- `byterator` doesn't support 64 bits operations.
Solution:
- Add readu64, peeku64 and writeu64 implementations.
=> :sparkles: Add uint64 support to `byterator`

include/stdx/ct_format.hpp, test/fail/CMakeLists.txt, test/fail/ct_format_mismatch.cpp
Problem:
- When a call to ct_format has a mismatch between the number of format specifiers and the number of arguments, the help message is obscure.
Solution:
- Provide a clearer help message.
=> :white_check_mark: :sound: Improve `ct_format` help message

test/to_underlying.cpp
Problem:
- `to_underlying` works with many types, but is only tested with enums and `int`.
Solution:
- Add template tests for more integral and floating-point types.
=> :white_check_mark: Add tests for `to_underlying` with arithmetic types

include/stdx/optional.hpp, test/optional.cpp
Problem:
- Sometimes it's desirable to select `stdx::optional` or `std::optional` based on whether tombstone_traits is specialized or not.
Solution:
- Add a `specialized` typedef to the primary template for tombstone_traits to allow easy identification.
=> :sparkles: Add easy way to select optional implementation

include/stdx/utility.hpp, test/utility.cpp
Problem:
- For some reason `constexpr` was omitted from `as_signed` and `as_unsigned` functions.
Solution:
- Make them `constexpr`.
=> :bug: Make `as_[un]signed` `constexpr`

include/stdx/span.hpp, test/span.cpp
Problem:
- When a dynamic span is constructed from an array, the size is not populated.
Solution:
- Initialize the base (size) properly.
=> :bug: Fix dynamic span construct from array

docs/bit.adoc, include/stdx/bit.hpp, test/bit.cpp
Problem:
- `smallest_uint` docs are incorrect.
Solution:
- `smallest_uint` takes the size required in bits.
Closes: #236
=> :bug: Fix the docs for `smallest_uint`

docs/ct_format.adoc, docs/ct_string.adoc
Problem:
- Documentation for `ct_format` is out of date.
Solution:
- Update it for the current functionality.
=> :books: Update docs for `ct_format`

include/stdx/compiler.hpp, include/stdx/ct_format.hpp, include/stdx/ct_string.hpp, include/stdx/tuple.hpp, include/stdx/udls.hpp
Problem:
- clang has a persistent regression where it ICEs with the error "trying to emit a call to an immediate function". This seems to be provoked by `consteval` UDLs.
Solution:
- When using clang, mark UDLs as `constexpr` rather than `consteval`.
=> :children_crossing: Workaround clang bug with consteval UDLs

CMakeLists.txt, include/stdx/ct_format.hpp, include/stdx/ct_string.hpp, include/stdx/pp_map.hpp, include/stdx/static_assert.hpp, include/stdx/utility.hpp, test/CMakeLists.txt, test/ct_format.cpp, test/ct_string.cpp, test/pp_map.cpp, test/utility.cpp
Problem:
- It is useful to have a macro that wraps a potentially-`constexpr`-usable value in `stdx::ct` when possible, to preserve its `constexpr` properties.
Solution:
- Add `CT_WRAP` that does this.
Notes:
- See https://github.com/intel/compile-time-init-build/pull/743 for some parts of this in CIB; this part probably belongs in stdx.
=> :sparkles: Add `CT_WRAP`

include/stdx/utility.hpp
Problem:
- `CX_VALUE` without a capture clause is important for use cases where the lambda has to be default constructible.
- Naming the function type in the `CX_WRAP` macro causes shadowing warnings.
Solution:
- Remove the default capture clause from `CX_VALUE`.
- Leave the function unnamed in `CX_WRAP`.
=> :bug: Small fixes for `CX_VALUE` and friends

include/stdx/utility.hpp
Problem:
- `CX_VALUE` without any capture clauses is important for use cases where the lambda has to be default constructible.
Solution:
- Remove the remaining default capture clauses from `CX_VALUE`.
=> :bug: Make `CX_VALUE` capture-free

include/stdx/ct_format.hpp
Problem:
- When converting a `format_result` to a `ct_string`, if it has runtime format arguments, the message does not make the contents of the `format_result` clear.
Solution:
- Use a better assertion.
Note:
- We cannot use a formatted `STATIC_ASSERT` here of course, because `ct_format` provides the mechanism for `STATIC_ASSERT`.
=> :children_crossing: Improve help message for `format_result` conversion

include/stdx/static_assert.hpp
Problem:
- Sometimes, `STATIC_ASSERT` may need to capture variables.
Solution:
- Use `[&]` as the capture spec in the `STATIC_ASSERT` lambda expressions.
=> :bug: Fix `STATIC_ASSERT` capture spec

include/stdx/utility.hpp, test/utility.cpp
Problem:
- When `CX_WRAP` wraps empty types, it doesn't turn them into `type_identity<T>`.
Solution:
- Move the emptiness check after the type check.
=> :bug: Fix `CX_WRAP` for empty types

include/stdx/bitset.hpp, include/stdx/utility.hpp
Problem:
- There are a couple of build issues flagged by clang-21.
Solution:
- Fix them.
=> :bug: Fix small issues for clang-21

docs/bit.adoc, include/stdx/bit.hpp, test/bit.cpp
Problem:
- Manual bit-shifting just to split a value into e.g. two pieces is still a thing. e.g. `auto x = val & 0x3; auto y = val >> 2;`
Solution:
- Introduce `bit_destructure`.
=> :sparkles: Add `bit_destructure`

include/stdx/utility.hpp
Problem:
- Type detection uses `+` and `*`.
Solution:
- Change to `+` and `-`.
=> :art: Change operator used for type detection

.github/workflows/unit_tests.yml
Problem:
- Mull 0.24.0 may be responsible for some false positives, and it is not the latest version.
Solution:
- Update to Mull 0.26.1.
=> :arrow_up: Update mull

include/stdx/optional.hpp, test/optional.cpp
Problem:
- Sometimes we want to use `std::optional` (not just `stdx::optional`) as an applicative functor.
Solution:
- Make multi-arg `transform` work on `std::optional` as well as `stdx::optional`.
=> :art: Make multi-arg `transform` work on `std::optional`

docs/utility.adoc, include/stdx/utility.hpp, test/utility.cpp
Problem:
- It's wordy to type `stdx::sized<std::uint8_t>{42}.in<std::uint32_t>();`.
Solution:
- Instead, allow `42_z8->z32;`
=> :sparkles: Add terse udls for size conversion

include/stdx/bit.hpp, include/stdx/ct_format.hpp, include/stdx/tuple.hpp, include/stdx/tuple_algorithms.hpp
Problem:
- `stdx` is not warning free with respect to `-Wnrvo`.
Solution:
- Add some trailing return types etc to fix warnings.
=> :rotating_light: Fix warnings arising from `-Wnrvo`

.github/workflows/usage_test.yml, .gitignore, docs/ct_format.adoc, docs/for_each_n_args.adoc, docs/function_traits.adoc, docs/static_assert.adoc, include/stdx/atomic_bitset.hpp, usage_test/CMakeLists.txt, usage_test/main.cpp
Problem:
- There is no usage test that includes all the headers.
- There is no usage test for freestanding implementations.
Solution:
- Add a usage test.
- Fix some usage in `atomic_bitset`. `::atomic` is a namespace in the `conc` library but `atomic` is a class template in `stdx`.
Note:
- Some functionality is not yet available for freestanding implementations, viz:
- `function_traits` and `for_each_n_args` use `std::function`
- `ct_format` and `static_assert` use libfmt
=> :sparkles: Add usage test

docs/call_by_need.adoc, include/stdx/call_by_need.hpp, test/call_by_need.cpp
Problem:
- If `call_by_need` calls a function returning a reference, it decays the result into the results tuple. It should preserve lvalue references generated in this way.
Solution:
- Preserve lvalue references in the results tuple.
=> :art: Make `call_by_need` deal with functions returning references
